apiVersion: v1
kind: Service
metadata:
  name: nodeport-daniel-henao
  namespace: namespace-daniel-henao
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80