apiVersion: v1
kind: Service
metadata:
  name: service-daniel-henao
  namespace: namespace-daniel-henao
spec:
  selector:
    app: httpd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007